
version: '3'

services:

  db:
    image: 'mysql:5.7'
    container_name: courseServiceDB
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      -  MYSQL_DATABASE: courselist